x-compose-project:
  project: python_redis_demo

version: "3"

services:
  webapp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "..:/app"
    depends_on:
        - redis

    # Redis
  redis:
    image: redis/redis-stack
    ports:
        - "6379:6379"
        - "8001:8001"
    volumes:
        - ./redis/data:/data
        - ./redis/redis.conf:/redis-stack.conf

volumes:
    redis_data:
